version: '3.5'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis

  backend:
    build: 
      dockerfile: $PWD/Dockerfile-backend
      context: ~/Programming/backend-example-docker
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=pass
      - DB_HOST=db
    ports:
      - 8000

  frontend:
    build:
      dockerfile: $PWD/Dockerfile-frontend
      context: ~/Programming/frontend-example-docker
    ports:
      - 5000
    environment:
      - API_URL=http://localhost/api

volumes:
  database:

