version: '3.5'

services:

  frontend:
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    networks:
      - default
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    volumes:
      - model:/src/model
    depends_on:
      - training
    networks:
      - default

  training:
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    volumes:
      - imgs:/src/imgs
      - model:/src/model

volumes:
  imgs:
  model:

networks:
  default:
