version: '3.5'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis

  backend:
    build: 
      dockerfile: $PWD/Dockerfile-backend
      context: ~/Programming/backend-example-docker
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=pass
      - DB_HOST=db
    depends_on:
      - redis
      - db

  frontend:
    build:
      dockerfile: $PWD/Dockerfile-frontend
      context: ~/Programming/frontend-example-docker
    ports:
      - 5000:5000

volumes:
  database:
