# docker build -t spring-example .
# docker run -d -p 8080:8080 spring-example
FROM openjdk:12-alpine

COPY . . 
RUN mvnw package
EXPOSE 8080
CMD ["java", "-jar", "./target/docker-example-1.1.3.jar"]
